In [1]:
import pandas as pd

In [2]:
csv_file = "mass_shootings.csv"
mass_shootings_df = pd.read_csv(csv_file)
mass_shootings_df.head()

,case,location,date,summary,fatalities,injured,total_victims,location.1,age_of_shooter,prior_signs_mental_health_issues,...,weapon_details,race,gender,sources,mental_health_sources,sources_additional_age,latitude,longitude,type,year
0,Uvalde elementary school massacre,"Uvalde, Texas",5/24/2022,DETAILS PENDING,15,-,-,School,18,-,...,-,-,M,https://abcnews.go.com/US/texas-elementary-sch...,-,-,-,-,Mass,2022
1,Buffalo supermarket massacre,"Buffalo, New York",5/14/2022,"Payton S. Gendron, 18, committed a racially mo...",10,3,13,workplace,18,yes,...,Bushmaster XM-15 semiautomatic rifle,White,M,https://www.nytimes.com/live/2022/05/15/nyregi...,https://www.nytimes.com/2022/05/15/nyregion/gu...,-,-,-,Mass,2022
2,Sacramento County church shooting,"Sacramento, California",2/28/2022,"""A man believed to be meeting his three childr...",4,0,4,Religious,-,-,...,-,-,M,https://www.nytimes.com/2022/02/28/us/church-s...,-,-,38.60111019,-121.4189659,Mass,2022
3,Oxford High School shooting,"Oxford, Michigan",11/30/2021,"Ethan Crumbley, a 15-year-old student at Oxfor...",4,7,11,School,15,-,...,Sig Sauer 9mm pistol,-,M,https://www.washingtonpost.com/nation/2021/11/...,-,-,42.84410784,-83.25992831,Mass,2021
4,San Jose VTA shooting,"San Jose, California",5/26/2021,"Samuel Cassidy, 57, a Valley Transportation Au...",9,0,9,Workplace,57,yes,...,-,-,M,https://www.sfchronicle.com/crime/article/Mass...,https://www.nytimes.com/2021/05/26/us/what-hap...,-,37.316097,-121.888533,Mass,2021

In [3]:
mass_shootings_df["state"] = mass_shootings_df["location"].apply(lambda x:x.split(",")[1])
mass_shootings_df.head()

,case,location,date,summary,fatalities,injured,total_victims,location.1,age_of_shooter,prior_signs_mental_health_issues,...,race,gender,sources,mental_health_sources,sources_additional_age,latitude,longitude,type,year,state
0,Uvalde elementary school massacre,"Uvalde, Texas",5/24/2022,DETAILS PENDING,15,-,-,School,18,-,...,-,M,https://abcnews.go.com/US/texas-elementary-sch...,-,-,-,-,Mass,2022,Texas
1,Buffalo supermarket massacre,"Buffalo, New York",5/14/2022,"Payton S. Gendron, 18, committed a racially mo...",10,3,13,workplace,18,yes,...,White,M,https://www.nytimes.com/live/2022/05/15/nyregi...,https://www.nytimes.com/2022/05/15/nyregion/gu...,-,-,-,Mass,2022,New York
2,Sacramento County church shooting,"Sacramento, California",2/28/2022,"""A man believed to be meeting his three childr...",4,0,4,Religious,-,-,...,-,M,https://www.nytimes.com/2022/02/28/us/church-s...,-,-,38.60111019,-121.4189659,Mass,2022,California
3,Oxford High School shooting,"Oxford, Michigan",11/30/2021,"Ethan Crumbley, a 15-year-old student at Oxfor...",4,7,11,School,15,-,...,-,M,https://www.washingtonpost.com/nation/2021/11/...,-,-,42.84410784,-83.25992831,Mass,2021,Michigan
4,San Jose VTA shooting,"San Jose, California",5/26/2021,"Samuel Cassidy, 57, a Valley Transportation Au...",9,0,9,Workplace,57,yes,...,-,M,https://www.sfchronicle.com/crime/article/Mass...,https://www.nytimes.com/2021/05/26/us/what-hap...,-,37.316097,-121.888533,Mass,2021,California

In [4]:
ms_df = mass_shootings_df[["state","year","summary"]]
ms_df

           state  year                                            summary
0          Texas  2022                                    DETAILS PENDING
1       New York  2022  Payton S. Gendron, 18, committed a racially mo...
2     California  2022  "A man believed to be meeting his three childr...
3       Michigan  2021  Ethan Crumbley, a 15-year-old student at Oxfor...
4     California  2021  Samuel Cassidy, 57, a Valley Transportation Au...
..           ...   ...                                                ...
123      Florida  1987  Retired librarian William Cruse, 59, was paran...
124     Oklahoma  1986  Postal worker Patrick Sherrill, 44, opened fir...
125   California  1984  James Oliver Huberty, 41, opened fire in a McD...
126        Texas  1984  Abdelkrim Belachheb, 39, opened fire at an ups...
127      Florida  1982  Junior high school teacher Carl Robert Brown, ...

[128 rows x 3 columns]

In [5]:
summary_ms = ms_df.groupby(["state","year"]).count()

In [6]:
summary_ms.value_counts()

summary
1          106
2            8
3            2
dtype: int64

In [7]:
summary_ms.head()

                  summary
state       year
 Arizona    2011        1
 Arkansas   1998        1
 California 1984        1
            1988        1
            1989        1